### ISSUE TITLE
Tried without tty but error

### ISSUE THREAD

**Issue by 9M2PJU** [VE3LSR/docker-linbpq#1]
services.linbpq.devices must be a list

**Comment by coolacid** [comment]
Thanks for reaching out. Can you give me some more details on what you're trying to do, and how you're trying to spawn the container?

**Comment by 9M2PJU** [comment]
I just want to up the telnet and aprs is

**Comment by coolacid** [comment]
Are you using the docker compose method to start? 

I suspect you need to review how to configure a service in docker compose, specifically the devices, and port lines.

**Comment by 9M2PJU** [comment]
Yes. docker compose.

**Comment by coolacid** [comment]
Can you share your docker-compose file? Have you read how to configure a docker-compose file?

**Comment by 9M2PJU** [comment]
i just comment out ttyUSB0

**Comment by coolacid** [comment]
You should remove the devices section too, as if you've added the devices stanza, docker compose expects there to be values.

**Comment by 9M2PJU** [comment]
got it. but can you build for arm64 too ?

**Comment by coolacid** [comment]
It's probably possible, But I've never built any docker image for use in Arm64, and wouldn't know where to begin, or how to grab the correct linbpq binary.

This wouldn't be a priority for me to work on right now. Sorry.

**Comment by 9M2PJU** [comment]
ok. understood
